version: "3.3"
services:

  db:
    image: postgres:10.18
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    container_name: fast-api-celery-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "54321:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  webserver:
    build: .
    ports:
      - "80:80"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432

  worker:
    build: .
    command: celery --app=app.worker.celery_app worker --loglevel=INFO --concurrency=1
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432

volumes:
  app-db-data:
