version: "3.3"
services:

  db:
    image: postgres:10.18
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    container_name: fast-api-celery-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "54321:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  app-db-data:
